# Generated by Django 2.0.7 on 2019-06-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='province',
        ),
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Institution'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='leader',
        ),
        migrations.AddField(
            model_name='province',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ManyToManyField(to='projects.Leader'),
        ),
    ]
