# Generated by Django 2.2.1 on 2019-06-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190603_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.ManyToManyField(to='projects.Province'),
        ),
    ]
